# Generated by Django 5.0.6 on 2024-06-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_frasedb_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frasedb',
            options={'verbose_name': 'Frase', 'verbose_name_plural': 'Frases'},
        ),
        migrations.AlterModelTable(
            name='frasedb',
            table='Frases',
        ),
    ]
