# Generated by Django 5.0.6 on 2024-06-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='frasedb',
            table='Frase',
        ),
    ]
