# Generated by Django 5.0.6 on 2024-06-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_melondb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='autordb',
            name='profesion',
        ),
        migrations.AddField(
            model_name='autordb',
            name='profesion',
            field=models.ManyToManyField(to='App1.profesion', verbose_name='Profesion'),
        ),
    ]
